from __future__ import annotations

import os
import re

from code_claim_verifier.types import TypedClaim, VerifiedClaim
from code_claim_verifier.security import safe_path

_GENERATED_MARKERS = [
    "DO NOT EDIT", "AUTO-GENERATED", "GENERATED BY", "Code generated by",
    "@generated", "auto-generated", "THIS FILE IS GENERATED",
]


def _find_file_in_repo(filename: str, repo_path: str) -> str | None:
    """Search for a file by name anywhere in the repo tree.
    Returns the first match or None."""
    basename = os.path.basename(filename)
    for root, _dirs, files in os.walk(repo_path):
        if basename in files:
            candidate = os.path.join(root, basename)
            if filename in candidate:
                return candidate
    return None


def verify_file_exists(claim: TypedClaim, repo_path: str, language: str) -> VerifiedClaim:
    path = claim.parameters.get("path", "")
    resolved = safe_path(path, repo_path)
    if resolved is None:
        return VerifiedClaim(claim=claim, verdict="REFUTED", method_confidence=0.99,
                             evidence="Path traversal detected", method="path_check")
    if os.path.isfile(resolved):
        return VerifiedClaim(
            claim=claim, verdict="VERIFIED", method_confidence=0.99,
            evidence=f"exists: {path}", method="os.path.isfile",
        )
    found = _find_file_in_repo(path, repo_path)
    if found:
        return VerifiedClaim(
            claim=claim, verdict="VERIFIED", method_confidence=0.90,
            evidence=f"exists (fuzzy match): {os.path.relpath(found, repo_path)}",
            method="os.walk_fuzzy",
        )
    return VerifiedClaim(
        claim=claim, verdict="REFUTED", method_confidence=0.99,
        evidence=f"not found: {path}", method="os.path.isfile",
    )


def verify_line_content(claim: TypedClaim, repo_path: str, language: str) -> VerifiedClaim:
    path = claim.parameters.get("file", claim.parameters.get("path", ""))
    line_num = claim.parameters.get("line", 0)
    expected = claim.parameters.get("expected_content", claim.parameters.get("expected", "")).strip()

    resolved = safe_path(path, repo_path)
    if resolved is not None and not os.path.isfile(resolved):
        found = _find_file_in_repo(path, repo_path)
        if found:
            resolved = found
    if resolved is None or not os.path.isfile(resolved):
        return VerifiedClaim(claim=claim, verdict="REFUTED", method_confidence=0.95,
                             evidence=f"File not found: {path}", method="file_read")
    try:
        with open(resolved, "r", encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
        if line_num < 1 or line_num > len(lines):
            return VerifiedClaim(claim=claim, verdict="REFUTED", method_confidence=0.95,
                                 evidence=f"Line {line_num} out of range (file has {len(lines)} lines)", method="file_read")
        actual = lines[line_num - 1].strip()
        match = expected in actual
        return VerifiedClaim(
            claim=claim, verdict="VERIFIED" if match else "REFUTED",
            method_confidence=0.95,
            evidence=f"Line {line_num}: {actual[:200]}",
            method="file_read",
        )
    except Exception as e:
        return VerifiedClaim(claim=claim, verdict="UNVERIFIABLE", method_confidence=0.0,
                             evidence="", method="file_read", error=str(e)[:200])


def verify_file_classification(claim: TypedClaim, repo_path: str, language: str) -> VerifiedClaim:
    path = claim.parameters.get("file", claim.parameters.get("path", ""))
    expected_cat = claim.parameters.get("category", "").lower()

    test_patterns = [r"test[s_/]", r"_test\.", r"\.test\.", r"spec[s_/]", r"e2e/", r"integration/", r"fixtures?/"]
    vendor_patterns = [r"vendor/", r"third_party/", r"node_modules/"]

    path_lower = path.lower()
    is_test = any(re.search(p, path_lower) for p in test_patterns)
    is_vendor = any(re.search(p, path_lower) for p in vendor_patterns)

    if expected_cat == "test":
        match = is_test
    elif expected_cat in ("vendored", "vendor"):
        match = is_vendor
    elif expected_cat == "production":
        match = not is_test and not is_vendor
    else:
        return VerifiedClaim(claim=claim, verdict="UNVERIFIABLE", method_confidence=0.0,
                             evidence=f"Unknown category: {expected_cat}", method="path_regex")

    return VerifiedClaim(
        claim=claim, verdict="VERIFIED" if match else "REFUTED",
        method_confidence=0.80, evidence=f"path={path}, is_test={is_test}, is_vendor={is_vendor}",
        method="path_regex",
    )


def verify_generated_or_vendored(claim: TypedClaim, repo_path: str, language: str) -> VerifiedClaim:
    path = claim.parameters.get("file", claim.parameters.get("path", ""))
    expected = claim.parameters.get("expected", True)

    resolved = safe_path(path, repo_path)
    if resolved is not None and not os.path.isfile(resolved):
        found = _find_file_in_repo(path, repo_path)
        if found:
            resolved = found
    if resolved is None or not os.path.isfile(resolved):
        return VerifiedClaim(claim=claim, verdict="REFUTED", method_confidence=0.85,
                             evidence=f"File not found: {path}", method="header_check")

    if "/vendor/" in path or "/third_party/" in path or "/node_modules/" in path:
        is_gen = True
    else:
        try:
            with open(resolved, "r", encoding="utf-8", errors="replace") as f:
                header = f.read(1000)
            is_gen = any(m in header for m in _GENERATED_MARKERS)
        except Exception:
            is_gen = False

    match = is_gen == expected
    return VerifiedClaim(
        claim=claim, verdict="VERIFIED" if match else "REFUTED",
        method_confidence=0.85, evidence=f"generated/vendored={is_gen}",
        method="header_check",
    )
